### ISSUE TITLE
Can not login using mysql after run

### ISSUE THREAD

**Issue by jwilsonGFM** [saltstack-formulas/mysql-formula#103]
I can not log in to mysql after I used this formula and set the following in pillar:

I have put in fake pass words and logins in this file:

[init_sls.txt](https://github.com/saltstack-formulas/mysql-formula/files/38455/init_sls.txt)

Otherwise Ive made no changes to the salt state files.

then ran it like so: 
sudo salt [Server_IP_Address] state.apply mysql

Then I try to login from either the jump server or the server where mysql was installed it fails:
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on '[Server_IP_Address]' (111)

I'm assuming I have failed to set some needed value in the pillar.

Any help would be appreciated.
Jeff Wilson

**Comment by gravyboat** [comment]
If there were no errors during the state run I'd suggest troubleshooting the server itself. Confirm the server was started, that it's listening on the correct port, and that you don't have any firewall issues.

**Comment by jwilsonGFM** [comment]
I tried changing the hist to "localhost" now I get this error:

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

Which is mysql login error. This implies that the root password is mapped to a different ip not %.

**Comment by gravyboat** [comment]
You'll probably want to make sure the users are configured properly, sometimes there have to be multiple users for both the localhost connection and the `%` connection. Do you believe this is related to the way the formula operates, or how you have the users configured? It seems as though the formula itself is working.

**Comment by gravyboat** [comment]
Did you get this figured out?

**Comment by jwilsonGFM** [comment]
Hello Forrest,
I wrote my own state to do this. I could never get any of the existing
states I found to work.

Jeff Wilson

**Comment by gravyboat** [comment]
Okay, if you have any changes to make to the formula feel free to put in a PR, I'm going to close this for now.
