### ISSUE TITLE
mysql.server failing to render

### ISSUE THREAD

**Issue by S-Wilhelm** [saltstack-formulas/mysql-formula#142]
On a Debian VM, Salt is printing the below messages:
`[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'version'
[CRITICAL] Rendering SLS 'base:mysql.server' failed: Jinja variable 'dict object' has no attribute 'version'
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:mysql.server' failed: Jinja variable 'dict object' has no attribute 'version'"]}`

The pillar.example doesn't include a 'version' entry, nor does the defaults.yaml .  The 'version' value is only noted on lines 67, 91, and 108 of server.sls .  Further, should lines 91 and 108 be 
`{% if ( os_family == 'RedHat' or os_family == 'Suse' ) and mysql.version >= 5.7 %}`
or
`{% if os_family == 'RedHat' or ( os_family == 'Suse' and mysql.version >= 5.7 ) %}`
instead?  As currently written, it appears to cause a check of mysql.version regardless of the OS family.

**Comment by babilen** [comment]
This might have been introduced in some of @Routhinator's recent changes, but I haven't checked in detail.

**Comment by mam08ixo** [comment]
Same here on an *Ubuntu 16.04.1 LTS* vm. For now, an earlier commit – I randomly picked [59fd786](https://github.com/saltstack-formulas/mysql-formula/commit/59fd786975b4149faf89b32094d0139b89765177) – gets things up and running again.

**Comment by gravyboat** [comment]
Resolved in #146
