### ISSUE TITLE
mysql-formula fails on openSUSE (wrong key in defaults.yaml)

### ISSUE THREAD

**Issue by cboltz** [saltstack-formulas/mysql-formula#156]
The mysql formula fails on openSUSE with
```
Rendering SLS 'production:mysql.server' failed: Jinja variable 'None' has no attribute 'server'
Rendering SLS 'production:mysql.server' failed: Jinja variable 'None' has no attribute 'server'
```

The reason is that default.yaml gets filtered by the 'os' grain - but doesn't include a matching key.

```
# salt '*' grains.get os
tux:   # openSUSE Tumbleweed
    openSUSE Tumbleweed
salt-test-1:   # openSUSE Leap 42.2
    SUSE
```

However default.yaml has "openSUSE" as a key, which doesn't match any of the above.

I can't speak for other distributions, but at least for openSUSE it would be a good idea to use the 'os_family' grain:

```
# salt '*' grains.get os_family
tux:  # openSUSE Tumbleweed
    Suse
salt-test-1:  # openSUSE Leap 42.2
    Suse
```

(CC @ccboltz)

**Comment by cboltz** [comment]
The above was with openSUSE Tumbleweed as salt master, and Tumbleweed and 42.2 as minion.

To make things more funny - with openSUSE Leap 42.1 (both master and minion), I get
```
salt '*' grains.get os
leap-42-1:
    openSUSE Leap
```

**Comment by aboe76** [comment]
I was looking into this: https://github.com/saltstack/salt/blob/develop/salt/grains/core.py

every os grain should be resolved:
```
if ":suse:" in os_release['CPE_NAME'] or ":opensuse:" in os_release['CPE_NAME']:
  grains['os'] = "SUSE"
```
So it should be SUSE, not openSUSE.

**Comment by cboltz** [comment]
#161 fixed this issue :-) - closing.
