### ISSUE TITLE
Python package incorrect for CentOS 5

### ISSUE THREAD

**Issue by Drachemann** [saltstack-formulas/mysql-formula#18]
The python package specified in the map.jinja file is incorrect for CentOS 5.
I'm not sure if this also affects Redhat

The correct package name is 'python26-mysqldb'
Not sure of the best way to fix this.. Obviously the grain "osmajorrelease" will allow determination of the os version..
Is there a way to add a further condition to the grains.filter_by in the map?

**Comment by noelmcloughlin** [comment]
#186 introduced osfamilymap and osmap. The Centos package should be fixed now.
