### ISSUE TITLE
Can't set mysql_grants on regexp anymore

### ISSUE THREAD

**Issue by Hybrid512** [saltstack-formulas/mysql-formula#180]
Hi,

Recently upgraded to Salt 2018.3.0 and suddenly my MySQL formula were not working anymore.
Allright, I upgraded the formula and here we go again, it works but, something that was working before don't work anymore.
Granting permissions to users with mysql_grants don't work with hots like this : 10.%
IP addresses are ok, hostnames are ok too but not net restrictions as it was before.

It seems mysql_grants dont quote the user/host combo and then, it issues that kind of command : 

> Failed to execute: "GRANT SELECT ON *.* TO user@10.%" (MySQL Error 1144: Illegal GRANT/REVOKE command; please consult the manual to see which privileges can be used)

I get the same error when typing the command in the MySQL cli but if I type this, it works (see the enclosing quotes) : 

> GRANT SELECT ON *.* TO 'user'@'10.%';

**Comment by noelmcloughlin** [comment]
@Hybrid512 See https://github.com/saltstack/salt/issues/41178

**Comment by noelmcloughlin** [comment]
@Hybrid512 can you pursue a fix in  saltstack/salt#41178 please.
