### ISSUE TITLE
Mysql 8 support

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/mysql-formula#189]
Hi

When adding users, mysql 8 throws the following error.

`Comment: MySQL Error 2059: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory`

The client on the zabbix server is also running mysql 8. I'm not sure where to go from here.

**Comment by noelmcloughlin** [comment]
Hey, according to the [release notes ](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html) you maybe need  `default_authentication_plugin=mysql_native_password` configured - Maybe this can be defined as pillar?

**Comment by waynegemmell** [comment]
This seemed to work ok. Now I'm locked out.
