### ISSUE TITLE
pillar lookup.server value is ignored

### ISSUE THREAD

**Issue by elmarshar** [saltstack-formulas/mysql-formula#56]
In Ubuntu 14.04 i'm setting lookup.server value in my pillar file as: mysql-server-5.6. This value is shown with the pillar.tems. However running salt-call --local state.highstate, installs the value from the defaults.yml, which is 'mysql-server'.
Changing the value in the defaults.yml, to mysql-server-5.6 works and the correct version gets installed.

**Comment by vschum** [comment]
Can you show the output of running:

`salt node pillar.get mysql:lookup:server`

**Comment by elmarshar** [comment]
I get the following result on with: salt-call --local pillar.get mysql:lookup:server
local:
    mysql-server-5.6

Forgot to mention I'm running: salt-call 2014.7.0 (Helium)

**Comment by tiger-seo** [comment]
+1 it should be  `mysql.lookup.server`
