### ISSUE TITLE
Use map.jinja as defaults store

### ISSUE THREAD

**Issue by refnode** [saltstack-formulas/mysql-formula#66]
This issue is a "duplicate" of #43 as I have also the problem to install MariaDB on CentOS 7.

The mysql formula should use map.as defaults store with grains.filter_by mechanism to provide a layered defaults store.

I'm working on a patch on my repo https://github.com/refnode/mysql-formula.git and send a pull request soon.

**Comment by vschum** [comment]
Have you tried using the mysql:lookup pillar key?

**Comment by refnode** [comment]
Sure, as a workaround and it's working.
Following the conventions in the apache formular, the layering of os_family, os and osmajorrelease makes sense for almost every network service formula and I think it would also reduce the redundant config values found in defaults.yaml.

I'll test my stuff now and push it asap.

**Comment by nmadhok** [comment]
@refnode MariaDb should be a formula on it's own and shouldn't been combined with mysql-formula. Mysql can still be installed on RHEL/CentOS 7 machines using the community repo. Obviously the support for that needs to be incorporated in this formula.

**Comment by refnode** [comment]
Ok, thx for info.
I close this issue and prepare a separate formula for that.

**Comment by nmadhok** [comment]
@refnode Thanks! Let me know when you have created the formula so we can fork it under ``saltstack-formulas`` :)

**Comment by refnode** [comment]
Sure!
