### ISSUE TITLE
Non-standard 'datadir' needs AppArmor changes on Ubuntu

### ISSUE THREAD

**Issue by eliasp** [saltstack-formulas/mysql-formula#81]
When using a non-standard `datadir` on Ubuntu, changes to AppArmor are required, otherwise MySQL won't start anymore.
See also: https://blogs.oracle.com/jsmyth/entry/apparmor_and_mysql

Similar changes are most likely required for SELinux enabled systems.

**Comment by noelmcloughlin** [comment]
See #88
