### ISSUE TITLE
mysql/defaults.yaml not found

### ISSUE THREAD

**Issue by c10b10** [saltstack-formulas/mysql-formula#85]
I'm getting the following error when I run the mysql state:

```
----------
          ID: mysql_config
    Function: file.managed
        Name: /etc/mysql/my.cnf
      Result: False
     Comment: Unable to manage file: Jinja error: mysql/defaults.yaml
              Traceback (most recent call last):
                File "/tmp/.root_4e6e95__salt/salt/utils/templates.py", line 306, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/tmp/.root_4e6e95__salt/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/tmp/.root_4e6e95__salt/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 7, in top-level template code
                File "/tmp/.root_4e6e95__salt/salt/utils/jinja.py", line 143, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: mysql/defaults.yaml

              ; line 7

              ---
              [...]
              # This config is generated by SALTSTACK
              # and all change will be overrided on next salt call
              {#-
              ===== FETCH DATA =====
              -#}
              {%- from "mysql/defaults.yaml" import rawmap with context -%}    <======================
              {%- from "mysql/supported_sections.yaml" import supported_sections with context -%}
              {%- set datamap = salt['grains.filter_by'](rawmap, grain='os', merge=salt['pillar.get']('mysql:server:lookup')) -%}
              {#-
              ===== COMBINE DATA =====
              -#}
              [...]
              ---
     Started: 16:42:01.829849
    Duration: 40.14 ms
     Changes:
```

**Comment by iggy** [comment]
File is definitely there. Maybe your git tree isn't getting updated properly?

https://github.com/saltstack-formulas/mysql-formula/blob/master/mysql/defaults.yaml

**Comment by iggy** [comment]
One other thing to note. If you change remotes for git trees, you're supposed to clear the master cache.

**Comment by c10b10** [comment]
I've set this up with direct inclusion in the top file. Could that affect
it?

Also, I've pruned the example pillar quite a bit. Are there values that are
mandatory?

**Comment by iggy** [comment]
Define "direct inclusion in the top file". Can you paste the relevant parts of your top file and your master config?

**Comment by c10b10** [comment]
- `master`

```
file_roots:
  base:
    - /Users/c10b10/Projects/forwardwd/salttest/salt
    - /Users/c10b10/Projects/forwardwd/salttest/formulas/mysql-formula
```

- `salt/top.sls`

```
base:
  '*':
    - core
    - tools.git
    - core.dotfiles
    - node
    - nginx
    - **mysql**
```

**Comment by c10b10** [comment]
Lots of problems.

I fixed the missing template errors by passing the variables from the `mysql_config` state to the `my.cnf` jinja template:

```
mysql_config:
  file.managed:
    - name: {{ mysql.config.file }}
    - template: jinja
    - source: salt://mysql/files/my.cnf
    - defaults:
      rawmap: {{ rawmap }}
      supported_sections: {{ supported_sections }}
```

Then, the `my.cnf` config file was created with a [trailing new space character](https://www.dropbox.com/s/3tr2z9on5insm80/Screenshot%202015-07-24%2012.56.21.png?dl=0), which I editing the last line of `mysql/files/my.cnf` to filter it out:

```
{{ datamap.config.append | default('') | replace("\\n","") }}
```

Now, I'm getting a permission denied error:

```
[ERROR   ] JSON Render failed for:
Permission denied, no authentication information
[ERROR   ] No JSON object could be decoded
```

**Comment by iggy** [comment]
So you hacked around a problem (instead of actually fixing it correctly), and then ran into more problems. Shocking. I suggest you figure out the original problem correctly.

**Comment by c10b10** [comment]
All the files were there, master cache was cleared, nothing worked. After hours of frustration I decided to drop the formula altogether and just write my own states. Thank you for your suggestion.

**Comment by iggy** [comment]
So we can close this issue then?

**Comment by c10b10** [comment]
yes

**Comment by gravyboat** [comment]
@c10b10 We've encountered a similar issue over here if you're using salt-ssh and there is a proposed solution: https://github.com/saltstack-formulas/mysql-formula/issues/92#issuecomment-144295341 otherwise we haven't been able to duplicate this on a setup using a masterless setup, or a master/minion setup.

**Comment by c10b10** [comment]
@gravyboat I was using salt-ssh. Thank you.

**Comment by gravyboat** [comment]
@c10b10 You got it! Hopefully this helps.
